### ISSUE TITLE
Disable the infernal keyboard sound

### ISSUE THREAD

**Issue by igel-kun** [simotek/Enlightenment-Themes#10]
I'm super happy that you re-published the old 'Dark' theme, since my laptop is not a phone :)
However, the artificial keyboard click sounds are killing me.
The mailing list (https://www.mail-archive.com/enlightenment-users@lists.sourceforge.net/msg27279.html) suggests to mute everything via the elementary settings, which seems to work but is really a shame because it also mutes alot of other things.

Maybe it's worth having a 'mute' version of the Dark theme that refrains from making peoples ears bleed :)

cheers

**Comment by rastermann** [comment]
just mute input... there's a reason there are multiple "virtual channels". you can mute a class of sound. key  presses, checkboxes toggling etc. all make some sounds under the input channel.

**Comment by simotek** [comment]
At one point I did actually remove all those sounds from the theme but these days raster is right.

**Comment by igel-kun** [comment]
Thanks for the comments and the explanation :)
